juegarte_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('juegarteadm/',include('sitio_admin.urls')),
    path('',include('sitio_cliente.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]
if settings.DEBUG==True:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio_admin/urls.py
from django.urls import path
from .views import agregararte, agregarjuego, cambiarestado, detallepedido, editararte, editarjuego, eliminararte, eliminarjuego, home, listaclientes, listaempleados, listapedidos
urlpatterns = [
    path('', home, name="home" ),
    path('agregarjuego/', agregarjuego, name="agregarjuego" ),
    path('agregararte/', agregararte, name="agregararte" ),
    path('editarjuego/<id>', editarjuego, name="editarjuego" ),
    path('editararte/<id>',editararte,name="editararte"),
    path('eliminarjuego/<id>',eliminarjuego, name="eliminarjuego" ),
    path('eliminararte/<id>',eliminararte,name="eliminararte"),
    path('listaclientes/',listaclientes,name="listaclientes"),
    path('listaempleados/',listaempleados,name="listaempleados"),
    path('listapedidos/',listapedidos,name="listapedidos"),
    path('listapedidos/detallepedido/<id>',detallepedido,name="detallepedidoadm"),
    path('listapedidos/cambiarestado/<id>/<tipo>',cambiarestado,name="cambiarestado"),
    
]

sitio_cliente/urls.py
from django.urls.conf import include
from sitio_cliente.views import home
from django.urls import path
from .views import Juegosrz, agregarartecarrito, agregarjuegocarrito, aumentarcantidad, carrito, catalogoarte, catalogojuegos, customLogin, detallearte, detallejuego, detallepedido, eliminaritem, generarpedido, home, listadopedidos, registro, restarcantidad
from rest_framework import routers

#para api
router=routers.DefaultRouter()
router.register('juegos',Juegosrz) 

urlpatterns = [
   path('',home,name="homecliente"),
   path('catalogojuegos/',catalogojuegos,name="catalogojuegos"),
   path('detallejuego/<id>',detallejuego,name="detallejuego"),
   path('catalogoarte/',catalogoarte,name="catalogoarte"),
   path('detallearte/<id>',detallearte,name="detallearte"),
   path('registro/',registro,name="registro"),
   path('carrito/',carrito,name="carrito"),
   path('catalogojuegos/agregarjuegocarrito/<id>',agregarjuegocarrito,name="agregarjuegocarrito"),
   path('catalogoarte/agregarartecarrito/<id>',agregarartecarrito,name="agregarartecarrito"),
   path('carrito/aumentarcantidad/<id>',aumentarcantidad,name="aumentarcantidad"),
   path('carrito/restarcantidad/<id>',restarcantidad,name="restarcantidad"),
   path('carrito/eliminaritem/<id>',eliminaritem,name="eliminaritem"),
   path('carrito/generarpedido',generarpedido,name="generarpedido"),
   path('pedidos/',listadopedidos,name="listadopedidos"),
   path('pedidos/detallepedido/<id>',detallepedido,name="detallepedido"),
   path('api/',include(router.urls)),
   
]

sitio_cliente/models.py
from django.db import models
from django.db.models.deletion import PROTECT
from django.core.validators import MinValueValidator, MaxValueValidator
from sitio_admin.models import *
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

puntaje=[('1','Pesimo'),
        ('2','Malo'),
        ('3','Regular'),
        ('4','Bueno'),
        ('5','Excelente'),
        ]

recomienda=[
    ('1','No lo Recomienda'),
    ('2','Lo Recomienda')
]  
tipo=[
    ('1','Juego'),
    ('2','Arte')
]  

estado=[
    ('1','Esperando deposito'),
    ('2','En camino'),
    ('3','Cerrado'),
    ('4','Cancelado'),
]
class reviewjuego(models.Model):
    idreview=models.AutoField(primary_key=True)
    juego=models.ForeignKey(Juego, on_delete=CASCADE, null=True)
    user=models.CharField(max_length=150)
    review=models.TextField(max_length=800,null=False)
    recomienda=models.CharField(max_length=1,choices=recomienda,default=2)


class reviewArte(models.Model):
    idreview=models.AutoField(primary_key=True)
    arte=models.ForeignKey(Arte,on_delete=CASCADE)
    user=models.CharField(max_length=150)
    review=models.TextField(max_length=800,null=False)
    recomienda=models.CharField(max_length=1,choices=recomienda,default=2)



class cart(models.Model):
    user=models.CharField(max_length=150,primary_key=True)    
    total=models.FloatField()
    def __str__(self):
        return self.user

class itemCarrito(models.Model):
    id=models.AutoField(primary_key=True)
    user=models.CharField(max_length=150)
    producto=models.CharField(max_length=250)
    precio=models.IntegerField()
    cantidad=models.IntegerField()
    subtotal=models.FloatField()
    

    

class Pedido(models.Model):
    id=models.AutoField(primary_key=True)
    user=models.CharField(max_length=150)
    fecha=models.DateTimeField(default=timezone.now)
    monto=models.IntegerField()
    estado=models.CharField(max_length=1,choices=estado,default='1')

class ItemPedido(models.Model):
    id=models.AutoField(primary_key=True)
    pedido=models.CharField(max_length=10)
    producto=models.CharField(max_length=250)
    precio=models.IntegerField()
    cantidad=models.IntegerField()
    subtotal=models.FloatField()


## class itemCarrito(models.Model):
#     id=models.AutoField(primary_key=True)
#     user=models.CharField(max_length=150)
#     producto=models.CharField(max_length=20)
#     es_juego=models.BooleanField(default=True)
        

sitio_cliente/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class formreviewjuego(forms.ModelForm):
    review=forms.Textarea(attrs={'class':'reviewuser'} )
    puntaje=forms.Select(attrs={'class':'selectpicker'})
    class Meta:
        model=reviewjuego
        fields=['review','recomienda']

class formreviewarte(forms.ModelForm):
     

     class Meta:
         model=reviewArte
         fields=['review','recomienda']


class FrmRegistro(UserCreationForm):
    class Meta:
        model=User
        fields=["username","email"]

class frmLog(forms.ModelForm):
    
    class Meta:
        model=User
        fields=["username","password"]

sitio_cliente/views.py
from django.db.models.query import InstanceCheckMeta
from django.shortcuts import get_object_or_404, redirect, render
from sitio_admin.models import Juego, Arte
from .forms import FrmRegistro, formreviewarte, formreviewjuego,frmLog
from .filters import filtroJuego,filtroArte
from .models import  ItemPedido, Pedido, cart, itemCarrito,  reviewArte, reviewjuego
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required,permission_required
# Create your views here.

def customLogin(request):
    form=frmLog()
    contexto={
        "form":form
    }
    if request.method=="POST":
        form=frmLog(data=request.POST)
        print(form)
        if form.is_valid():
            user=authenticate(username=form.cleaned_data["username"],password=form.cleaned_data["password"])
            tipo=User.objects.filter(username=form.cleaned_data["username"])
            login(request,user)
            print("***********SI HIZO LOGIN*********************")
            if tipo==1:
                
                return redirect(to="sitio_admin/home.html")
            else:
                return redirect(to="home")
        else:
            print("***********No válido*********************")

    return render(request,"registration/frmLog.html",contexto)

def home(request):
    juegos=Juego.objects.all().filter(estado=1).order_by("idjuego")
    arte=Arte.objects.all().filter(estado=1).order_by("idarte")
    contexto={
        "juegos":juegos,
        "arte":arte
    }
    return render(request,"sitio_cliente/home.html",contexto)


def catalogojuegos(request):
    juegos=Juego.objects.all().filter(estado=1).order_by("idjuego")
    filtro=filtroJuego(request.GET,queryset=juegos)
    juegos=filtro.qs
    contexto={
        "juegos":juegos, "filtro":filtro,
       
    }

    return render(request,"sitio_cliente/catalogojuegos.html",contexto)


def detallejuego(request,id):
    juego=get_object_or_404(Juego,idjuego=id)
    formulario=formreviewjuego(request.POST or None)
    reviews=reviewjuego.objects.filter(juego_id=id)
    reviewuser=reviewjuego.objects.all()
    poseereview=0
    for item in reviewuser:
        if item.user== request.user.username and item.juego==juego:
            poseereview=1

    contexto={
        "juego":juego,
        "formulario":formulario,
        "reviews":reviews,
        "poseereview":poseereview
    }   
    if request.method=="POST":
        if formulario.is_valid():
            rev=reviewjuego()
            datos=formulario.cleaned_data
            rev.juego=juego
            rev.user=request.user.username
            rev.review=datos.get("review")
            rev.recomienda=datos.get("recomienda")
            rev.save()
            return redirect(to="catalogojuegos")
    return render(request,"sitio_cliente/detallejuego.html",contexto)


def catalogoarte(request):
    arte= Arte.objects.all().filter(estado=1).order_by("idarte")
    filtro=filtroArte(request.GET,queryset=arte)
    arte=filtro.qs
    contexto={
        "arte":arte,
        "filtro":filtro
    }

    return render(request,"sitio_cliente/catalogoarte.html",contexto)

def detallearte(request,id):
    arte=get_object_or_404(Arte,idarte=id)
    formulario=formreviewarte(request.POST or None)
    reviews=reviewArte.objects.all().filter(arte_id=id)
    reviewuser=reviewArte.objects.all()
    poseereview=0
    for item in reviewuser:
        if item.user == request.user.username and item.arte==arte:
            poseereview=1

    contexto={
        "arte":arte,
        "formulario":formulario,
        "reviews":reviews,
        "poseereview":poseereview
    }
    if request.method=="POST":
        if formulario.is_valid():
            rev=reviewArte()
            datos=formulario.cleaned_data
            rev.arte=arte
            rev.user=request.user.username
            rev.review=datos.get("review")
            rev.recomienda=datos.get("recomienda")
            rev.save()
            return redirect(to="catalogoarte")
    return render(request,"sitio_cliente/detallearte.html",contexto)    



def registro(request):
    form=FrmRegistro()

    contexto={
        "form":form
    }

    if request.method=="POST":
        form=FrmRegistro(data=request.POST)
        
        if form.is_valid():
            form.save()
            return redirect(to="login")
    return render(request,'registration/registro.html',contexto)        



@login_required
def carrito(request):
    carritos=cart.objects.all()
    tienecarrito=0
    for carrito in carritos:
        if carrito.user==request.user.username:
            tienecarrito=1
    
    if tienecarrito==1:
        carro=cart.objects.get(user=request.user.username)
        items=itemCarrito.objects.all().filter(user=request.user.username)
    else:
        carro=cart()
        carro.user=request.user.username
        carro.total=0
        carro.save()
        items=itemCarrito.objects.all().filter(user=request.user.username)
    total=0

    contexto={
       'items':items ,
       'carro':carro
       
    }
    return render(request,'sitio_cliente/carrito.html',contexto)

@login_required
def agregarjuegocarrito(request,id):
    carritos=cart.objects.all()
    item=Juego.objects.get(idjuego=id)
    juegoscarrito=itemCarrito.objects.all()
    existeitem=0
    tienecarrito=0
    for juego in juegoscarrito:
        if juego.user==request.user.username and juego.producto==item.nombrejuego:
            existeitem=1
    for carrito in carritos:
        if carrito.user==request.user.username:
            tienecarrito=1


    if tienecarrito==0:
        nuevo=cart()
        nuevo.user=request.user.username
        nuevo.total=0
        nuevo.save()

    if existeitem==0:
        nuevoitem=itemCarrito()
        nuevoitem.user=request.user.username
        nuevoitem.producto=item.nombrejuego
        nuevoitem.precio=item.preciojuego
        nuevoitem.cantidad=1
        nuevoitem.subtotal=item.preciojuego
        nuevoitem.save()
        carrito=cart.objects.get(user=request.user.username)
        carrito.total+=nuevoitem.subtotal
        carrito.save()
    elif existeitem==1:
        updateitem=itemCarrito.objects.get(producto=item.nombrejuego,user=request.user.username)
        updateitem.precio=item.preciojuego
        updateitem.cantidad+=1
        updateitem.subtotal=updateitem.precio*updateitem.cantidad
        updateitem.save()
        carrito=cart.objects.get(user=request.user.username)
        carrito.total+=updateitem.precio
        carrito.save()
    
   
    return redirect(to="catalogojuegos")

@login_required
def agregarartecarrito(request,id):
    carritos=cart.objects.all()
    item=Arte.objects.get(idarte=id)
    artecarrito=itemCarrito.objects.all()
    existeitem=0
    tienecarrito=0
    for arte in artecarrito:
        if arte.user==request.user.username and arte.producto==item.nombrearte:
            existeitem=1
    for carrito in carritos:
        if carrito.user==request.user.username:
            tienecarrito=1


    if tienecarrito==0:
        nuevo=cart()
        nuevo.user=request.user.username
        nuevo.total=0
        nuevo.save()

    if existeitem==0:
        nuevoitem=itemCarrito()
        nuevoitem.user=request.user.username
        nuevoitem.producto=item.nombrearte
        nuevoitem.precio=item.precioarte
        nuevoitem.cantidad=1
        nuevoitem.subtotal=item.precioarte
        nuevoitem.save()
        carrito=cart.objects.get(user=request.user.username)
        carrito.total+=nuevoitem.subtotal
        carrito.save()
    elif existeitem==1:
        updateitem=itemCarrito.objects.get(producto=item.nombrearte,user=request.user.username)
        updateitem.precio=item.precioarte
        updateitem.cantidad+=1
        updateitem.subtotal=updateitem.precio*updateitem.cantidad
        updateitem.save()
        carrito=cart.objects.get(user=request.user.username)
        carrito.total+=updateitem.precio
        carrito.save()
    
   
    return redirect(to="catalogoarte")


@login_required
def aumentarcantidad(request,id):
    item=itemCarrito.objects.get(id=id)
    carrito=cart.objects.get(user=request.user.username)

    item.cantidad+=1
    item.subtotal=item.precio*item.cantidad
    item.save()
    carrito.total+=item.precio
    carrito.save()

    return redirect(to="carrito")
@login_required
def restarcantidad(request,id):
    item=itemCarrito.objects.get(id=id)
    carrito=cart.objects.get(user=request.user.username)

    item.cantidad-=1
    item.subtotal=item.precio*item.cantidad
    item.save()
    carrito.total-=item.precio
    carrito.save()
    return redirect(to="carrito")

@login_required
def eliminaritem(request,id):
    item=itemCarrito.objects.get(id=id)
    carrito=cart.objects.get(user=request.user.username)
    carrito.total-=item.subtotal
    carrito.save()
    item.delete()
    return redirect(to="carrito")

@login_required
def generarpedido(request):
    carritoped=cart.objects.get(user=request.user.username)
    itemscarrito=itemCarrito.objects.all().filter(user=request.user.username)
    nuevopedido=Pedido()
    
    nuevopedido.user=request.user.username
    nuevopedido.monto=carritoped.total
    nuevopedido.save()
    for item in itemscarrito:
        print(item.producto)
        itemspedido=ItemPedido()
        itemspedido.pedido=nuevopedido.id
        itemspedido.producto=item.producto
        itemspedido.precio= item.precio
        itemspedido.cantidad=item.cantidad
        itemspedido.subtotal=item.subtotal
        itemspedido.save()
        item.delete()

    carritoped.total=0
    carritoped.save()
    

    return redirect(to="homecliente")

@login_required
def listadopedidos(request):
    pedidos=Pedido.objects.all().filter(user=request.user.username)

    contexto={
        'pedidos':pedidos
    }
    return render(request,'sitio_cliente/listadopedidos.html',contexto)

@login_required
def detallepedido(request,id):

sitio_cliente/templates/sitio_cliente/detallearte.html
{% extends 'sitio_cliente/base.html' %}
{%load static %}
{%load crispy_forms_tags%}
{% block head %}
<link rel="stylesheet" href="{% static 'sitio_cliente/css/cliente.css' %}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&family=PT+Serif&display=swap" rel="stylesheet">

<style>
    body{
        background-color: #8B78FF;
        font-family: 'Oswald', sans-serif;
       
    }
 </style>  
{% endblock head %}


{% block contenido %}
<script>
    $(document).ready(function () {
         
        $.getJSON("https://mindicador.cl/api", function (datos) {
               // alert(datos.dolar.valor);
               var dolarv= datos.dolar.valor;
               var eurov= datos.euro.valor;
               var valorproducto= parseInt($("#valorpeso").text());
               var preciodolar=valorproducto/dolarv;
               var preciodolar= preciodolar.toString();
               var usdshort= jQuery.trim(preciodolar).substring(0,4)
               var precioeuro= valorproducto/eurov;
               var precioeuro= precioeuro.toString()
               var euroshort= jQuery.trim(precioeuro).substring(0,4)
               $('#valordolar').text("$"+usdshort+"USD")
               $("#valoreuro").text("$"+euroshort+"EUR")


        })        
    });



</script>


<script>
    $(document).ready(function () {
        $("select").selectpicker()
    });


function agregarcarrito(id){

Swal.fire({
   title:"¿Desea agregar juego a carrito?",
   
   showConfirmButton: true,
   confirmButtonColor: "green",
   confirmButtonText:"Agregar",

   showCancelButton: true,
   cancelButtonText:"Cancelar",
  
}).then(function(result){
   if(result.isConfirmed){
       window.location.href= "http://127.0.0.1:8000/catalogoarte/agregarartecarrito/" + id;
   }
});

}

</script>
<section id="detallejuego">
    <div class="container mt-5">
        <div class="row ">
            <div class="col-lg-8 col-sm-12">
                {% if arte.imagen %}
                        <img src="{{arte.imagen.url}}" class="imgcarousel" alt="Los Angeles">
                    {% else %}
                        <img src="{% static 'sitio_cliente/img/Enconstruccion.jpg' %}" class="imgcarousel" alt="Los Angeles">
                    {% endif %}
                
            </div>
            <div class="col-lg-4 col-sm-12">
                <div class="card bg-dark text-white h-100">
                    <div class="card-body h-100 d-flex flex-column text-center">
                      <h4 class="card-title text-center">{{arte.nombrearte}}</h4>
                      <p class="card-text text-center" id="descripcionjuego">{{arte.descripcion}}</p>
                       <p class="card-text">Categoria:{{arte.categoria}}</p> 
                       <p class="card-text">Dimensiones:{{arte.dimensiones}}</p> 
                       <p class="card-text">Precio:$<span id="valorpeso">{{arte.precioarte}}</span>CLP, <span id="valordolar"></span>, <span id="valoreuro"></span></p>
                    </div>
                  </div>
            </div>
        </div>
    </div>
    <div class="container mt-3">
        <div class="row">
            
            <div class="col-lg-6 offset-lg-3 col-sm-12 ">
                <button class="btn btn-block btn-outline-success " onclick="agregarcarrito({{arte.idarte}})" style="color:#FF5733   ;background-color: #581845;"><i class="fas fa-cart-plus" ></i>  Agregar a carrito</button>
            </div>
        </div>

    </div>
</section>

<section id="reviewsjuego">
    <div class="container mt-5">
        <h3 class="text-center">Reseñas producto</h3>
        {% if poseereview == 0 %}
            <h5 class="text-center mt-3 mb-1">Deja tu reseña</h5>
        <div class="row" id="userreview">
            <div class="col-lg-2 col-sm-12">

            </div>
            <div class="col-lg-8 col-sm-12">
                <form action="" method="POST" enctype="multipart/form-data " id="formreview">
                    {% csrf_token %}
                    {{formulario|crispy}}
                    <input type="submit" class="btn  btn-secondary mb-5" style="color:#FF5733  ;background-color: #581845;" value="Publica tu reseña">
                </form>
            </div>
        {% endif %}
        
        </div>
        

    </div>
    <div class="container bg-secondary mb-4" style="border-radius: 35px 35px 25px 25px ;">
        <h5 class="text-center mt-3 mb-3">Reseña usuarios</h5>

        {% if not reviews %}
            <div class="row mt-3 mb-0">
            <div class="col-lg-2 col-sm-12 reviewown  text light" >
                <p class="pt-4 pl-5">{{item.user}}</p>
            </div>
            <div class="col-lg-9 col-sm-12 reviewdetail bg-dark text-light mb-2 " style="font-family: 'PT Serif', serif; ">
                <div>
                    <h5 class="pt-3"></h5>
                </div>
                <p class="text-center pr-5">Actualmente no hay reviews</p>
                
            </div>
            {% endif %}
        {% for item in reviews %}
        
        <div class="row mt-3 mb-5">
            <div class="col-lg-2 col-sm-12 reviewown  text light" >
                <p class="pt-4 pl-5" style="font-weight: 900;">
                    <i class="fas fa-user-circle"></i>
                    {{item.user}}</p>
            </div>
            <div class="col-lg-9 col-sm-12 reviewdetail bg-dark text-light mb-2 " style="font-family: 'PT Serif', serif; ">
                <div>
                    <h5 class="pt-3">{{item.get_recomienda_display}}</h5>
                </div>
                <p>{{item.review}}</p>
                
            </div>
        </div>
        
        

        
        {% endfor %}
    </div>

     
    
</section>


{% endblock contenido %}

sitio_cliente/templates/sitio_cliente/detallejuego.html
{% extends 'sitio_cliente/base.html' %}
{%load static %}
{%load crispy_forms_tags%}
{% block head %}
<link rel="stylesheet" href="{% static 'sitio_cliente/css/cliente.css' %}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&family=PT+Serif&display=swap" rel="stylesheet">

<style>
    body{
        background-color: #8B78FF;
        font-family: 'Oswald', sans-serif;
       
    }
 </style>  
{% endblock head %}


{% block contenido %}
<script>
    $(document).ready(function () {
         
        $.getJSON("https://mindicador.cl/api", function (datos) {
               // alert(datos.dolar.valor);
               var dolarv= datos.dolar.valor;
               var eurov= datos.euro.valor;
               var valorproducto= parseInt($("#valorpeso").text());
               var preciodolar=valorproducto/dolarv;
               var preciodolar= preciodolar.toString();
               var usdshort= jQuery.trim(preciodolar).substring(0,4)
               var precioeuro= valorproducto/eurov;
               var precioeuro= precioeuro.toString()
               var euroshort= jQuery.trim(precioeuro).substring(0,4)
               $('#valordolar').text("$"+usdshort+"USD")
               $("#valoreuro").text("$"+euroshort+"EUR")


        })        
    });



</script>


<script>
    $(document).ready(function () {
        $("select").selectpicker()
    });


function agregarcarrito(id){

Swal.fire({
   title:"¿Desea agregar juego a carrito?",
   
   showConfirmButton: true,
   confirmButtonColor: "green",
   confirmButtonText:"Agregar",

   showCancelButton: true,
   cancelButtonText:"Cancelar",
  
}).then(function(result){
   if(result.isConfirmed){
       window.location.href= "http://127.0.0.1:8000/catalogojuegos/agregarjuegocarrito/" + id;
   }
});

}

</script>
<section id="detallejuego "  >
    <div class="container mt-5">
        <div class="row ">
            <div class="col-lg-8 col-sm-12">
                {% if juego.imagen %}
                 <img src="{{juego.imagen.url}}" class="imgcarousel" alt="Los Angeles">
                {% else %}
                 <img src="{% static 'sitio_cliente/img/Enconstruccion.jpg' %}" class="imgcarousel" alt="Los Angeles">
                {% endif %}
               
            </div>
            <div class="col-lg-4 col-sm-12">
                <div class="card bg-dark text-white h-100">
                    <div class="card-body h-100 d-flex flex-column text-center">
                      <h4 class="card-title text-center">{{juego.nombrejuego}}</h4>
                      <p class="card-text text-center" id="descripcionjuego">{{juego.descripcion}}</p>
                       <p class="card-text">Categoria:{{juego.categoria}}</p> 
                       <p class="card-text">Precio:$<span id="valorpeso">{{juego.preciojuego}}</span>CLP, <span id="valordolar"></span>, <span id="valoreuro"></span></p>
                    </div>
                  </div>
            </div>
        </div>
    </div>
    <div class="container mt-3">
        <div class="row">
            
            <div class="col-lg-6 offset-lg-3 col-sm-12 ">
                <button class="btn btn-block btn-outline-success "onclick="agregarcarrito({{juego.idjuego}})" style="color:#FF5733  ;background-color: #581845;"><i class="fas fa-cart-plus" ></i>  Agregar a carrito</button>
            </div>
        </div>

    </div>
</section>

<section id="reviewsjuego">
    <div class="container mt-5">
        <h3 class="text-center">Reseñas producto</h3>
        {% if poseereview == 0 %}
            <h5 class="text-center mt-3 mb-1">Deja tu reseña</h5>
        <div class="row" id="userreview">
            <div class="col-lg-2 col-sm-12">

            </div>
            <div class="col-lg-8 col-sm-12">
                <form action="" method="POST" enctype="multipart/form-data " id="formreview">
                    {% csrf_token %}
                    {{formulario|crispy}}
                    <input type="submit" class="btn  btn-secondary mb-5" style="color:#FF5733  ;background-color: #581845;" value="Publica tu reseña">
                </form>
            </div>
        {% endif %}
        
        </div>
        

    </div>
    <div class="container bg-secondary mb-3" style="border-radius: 35px 35px 25px 25px ;">
        <h5 class="text-center mt-3 mb-3">Reseña usuarios</h5>

        {% if not reviews %}
            <div class="row mt-3 mb-0">
            <div class="col-lg-2 col-sm-12 reviewown  text light" >
                <p class="pt-4 pl-5">{{item.user}}</p>
            </div>
            <div class="col-lg-9 col-sm-12 reviewdetail bg-dark text-light mb-2 " style="font-family: 'PT Serif', serif; ">
                <div>
                    <h5 class="pt-3"></h5>
                </div>
                <p class="text-center pr-5">Actualmente no hay reviews</p>
                
            </div>
            {% endif %}
        {% for item in reviews %}
        
        <div class="row mt-3 mb-0">
            <div class="col-lg-2 col-sm-12 reviewown  text light" >
                <p class="pt-4 pl-5" style="font-weight: 900;">
                    <i class="fas fa-user-circle"></i>
                    {{item.user}}</p>
            </div>
            <div class="col-lg-9 col-sm-12 reviewdetail bg-dark text-light mb-2 " style="font-family: 'PT Serif', serif; ">
                <div>
                    <h5 class="pt-3">{{item.get_recomienda_display}}</h5>
                </div>
                <p>{{item.review}}</p>
                
            </div>
        </div>
        
        

        
        {% endfor %}
    </div>

     
    
</section>


{% endblock contenido %}

sitio_cliente/templates/sitio_cliente/listadopedidos.html
{% extends 'sitio_cliente/base.html' %}
{% load static %}

{% block contenido %}

<section>
    <div class="container">
        <h3 class="mt-5 mb-4 text-center">Listado de pedidos</h3>
        <table class="table table-responsive-lg table-striped" style="background-color:#FFD187;">
            <thead class="bg-dark text-light">
                <th>ID</th>
                <th>Fecha</th>
                <th>Total</th>
                <th>Estado</th>
                <th>Detalle</th>

            </thead>
            <tbody>
            {% for pedido in pedidos  %}
                 <tr>
                    <td>{{pedido.id}}</td>
                    <td>{{pedido.fecha}}</td>
                    <td>${{pedido.monto}}</td>
                    <td>{{pedido.get_estado_display}}</td>
                    <td><a href="{% url 'detallepedido' pedido.id %}" class="btn btn-outline-info"><i class="fas fa-info-circle"></i></a></td>
                </tr>
            
            {% endfor %}
               
            </tbody>
        </table>

    </div>
</section>

{% endblock contenido %}