juegarte_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('juegarteadm/',include('sitio_admin.urls')),
    path('',include('sitio_cliente.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]
if settings.DEBUG==True:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio_admin/urls.py
from django.urls import path
from .views import agregararte, agregarjuego, cambiarestado, detallepedido, editararte, editarjuego, eliminararte, eliminarjuego, home, listaclientes, listaempleados, listapedidos
urlpatterns = [
    path('', home, name="home" ),
    path('agregarjuego/', agregarjuego, name="agregarjuego" ),
    path('agregararte/', agregararte, name="agregararte" ),
    path('editarjuego/<id>', editarjuego, name="editarjuego" ),
    path('editararte/<id>',editararte,name="editararte"),
    path('eliminarjuego/<id>',eliminarjuego, name="eliminarjuego" ),
    path('eliminararte/<id>',eliminararte,name="eliminararte"),
    path('listaclientes/',listaclientes,name="listaclientes"),
    path('listaempleados/',listaempleados,name="listaempleados"),
    path('listapedidos/',listapedidos,name="listapedidos"),
    path('listapedidos/detallepedido/<id>',detallepedido,name="detallepedidoadm"),
    path('listapedidos/cambiarestado/<id>/<tipo>',cambiarestado,name="cambiarestado"),
    
]

sitio_admin/models.py
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT

# Create your models here.
Estadoproducto=[
    ("1","Disponible"),
    ("2","Oculto")
]
class Categoriajuego(models.Model):
    idcategoria=models.AutoField(primary_key=True)
    nombrecategoria=models.CharField(max_length=50,null=False)
   

    def __str__(self):
        return self.nombrecategoria

class Categoriaarte(models.Model):
    idcategoria=models.AutoField(primary_key=True)
    nombrecategoria=models.CharField(max_length=50,null=False)
   

    def __str__(self):
        return self.nombrecategoria


class Juego(models.Model):
    idjuego=models.AutoField(primary_key=True)
    nombrejuego=models.CharField(max_length=300,null=False)
    preciojuego=models.IntegerField(null=False)
    descripcion=models.TextField(max_length=800,null=False)
    categoria=models.ForeignKey(Categoriajuego,on_delete=CASCADE ,default=1)
    estado=models.CharField(max_length=1,choices=Estadoproducto,default="1")
    imagen=models.ImageField(upload_to="imagenes",null=True)

    def __str__(self):
        return self.nombrejuego
    

class Arte(models.Model):
    idarte=models.AutoField(primary_key=True)
    nombrearte=models.CharField(max_length=150,null=False)
    precioarte=models.IntegerField(null=False)
    descripcion=models.TextField(max_length=500,null=False)
    dimensiones=models.CharField(max_length=100)
    categoria=models.ForeignKey(Categoriaarte, on_delete=CASCADE, default=1)
    estado=models.CharField(max_length=1,choices=Estadoproducto,default="1")
    imagen=models.ImageField(upload_to="imagenes",null=True)

    def __str__(self):
        return self.nombrearte

sitio_admin/forms.py
from django import forms
from django.db.models import fields
from .models import Arte, Juego

class formJuego(forms.ModelForm):
    
    categoria=forms.SelectMultiple(attrs={'class':'selectpicker'})
     
    class Meta:
        model=Juego
        fields=["nombrejuego","preciojuego","descripcion","categoria","estado","imagen"]

  

class formArte(forms.ModelForm):


    class Meta:
        model=Arte
        fields=["nombrearte","precioarte","descripcion","dimensiones","categoria","estado","imagen"]

sitio_admin/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import formArte, formJuego
from django.shortcuts import get_object_or_404, redirect, render
from .models import Juego,Arte
from sitio_cliente.models import Pedido, ItemPedido
from django.contrib.auth.decorators import login_required,permission_required
# Create your views here.
@login_required
@permission_required('sito_admin.can_add_arte')
def home(request):
    juegos=Juego.objects.all().order_by("idjuego")
    arte=Arte.objects.all().order_by("idarte")
    contexto={
        "juegos":juegos,
        "arte":arte
    }
    
    return render(request,"sitio_admin/home.html",contexto)

@login_required
@permission_required('sito_admin.can_add_arte')
def agregarjuego(request):
    formulario=formJuego(request.POST or None)
    contexto={
        "form":formulario
    }
    if request.method=="POST":
        formulario=formJuego(data=request.POST,files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="home")
    return render(request, "sitio_admin/agregarjuego.html",contexto)    

@login_required
@permission_required('sito_admin.can_add_arte')
def agregararte(request):
    formulario=formArte(request.POST or None)
    contexto={
        "form":formulario
    }
    if request.method=="POST":
        formulario=formArte(data=request.POST,files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,"Arte Agregado")
            return redirect(to="home")
    return render(request, "sitio_admin/agregararte.html",contexto)


@login_required
@permission_required('sito_admin.can_add_arte')
def editarjuego(request,id):
    juego=get_object_or_404(Juego,idjuego=id)
    formulario=formJuego(instance=juego)
    
    contexto={
        "form":formulario
    }    


    if request.method=="POST":
        formulario=formJuego(data=request.POST,instance=juego,files=request.FILES)

        if formulario.is_valid():
            jmod=Juego.objects.get(idjuego=juego.idjuego)
            datos=formulario.cleaned_data

            jmod.idjuego=juego.idjuego
            jmod.nombrejuego=datos.get("nombrejuego")
            jmod.preciojuego=datos.get("preciojuego")
            jmod.descripcion=datos.get("descripcion")
            jmod.categoria=datos.get("categoria")
            jmod.estado=datos.get("estado")
            jmod.imagen=datos.get("imagen")
            jmod.save()
            
            

            
                
            messages.success(request,"Juego Modificiado")

            return redirect(to="home")

        contexto={
            "form":formulario
        }
    return render(request,"sitio_admin/editarjuego.html",contexto)    


@login_required
@permission_required('sito_admin.can_add_arte')
def eliminarjuego(request,id):
    juego=get_object_or_404(Juego,idjuego=id)
    juego.delete()

    return redirect(to="home")


@login_required
@permission_required('sito_admin.can_add_arte')
def editararte(request,id):
    arte=get_object_or_404(Arte,idarte=id)
    formulario=formArte(instance=arte)

    contexto={
        "form":formulario
    }  

    if request.method=="POST":
        formulario=formArte(data=request.POST,instance=arte,files=request.FILES)

        if formulario.is_valid():
            amod=Arte.objects.get(idarte=arte.idarte)
            datos=formulario.cleaned_data

            amod.idarte=arte.idarte
            amod.nombrearte=datos.get("nombrearte")
            amod.precioarte=datos.get("precioarte")
            amod.descripcion=datos.get("descripcion")
            amod.dimensiones=datos.get("dimensiones")
            amod.categoria=datos.get("categoria")
            amod.estado=datos.get("estado")
            amod.imagen=datos.get("imagen")
            amod.save()

            messages.success(request,"Arte Modificiado")
            return redirect(to="home")

        contexto={
            "form":formulario
        }
    return render(request,"sitio_admin/editararte.html",contexto)


@login_required
@permission_required('sito_admin.can_add_arte')
def eliminararte(request,id):
    arte=get_object_or_404(Arte,idarte=id)
    arte.delete()

    return redirect(to="home")


@login_required
@permission_required('sito_admin.can_add_arte')
def listaclientes(request):
    usuarios=User.objects.all().filter(is_staff=False)
    contexto={
        'usuarios':usuarios

    }
    return render(request,"sitio_admin/listaclientes.html",contexto)

@login_required
@permission_required('sito_admin.can_add_arte')
def listaempleados(request):
    usuarios=User.objects.all().filter(is_staff=True)
    contexto={
        'usuarios':usuarios

    }
    return render(request,"sitio_admin/listaempleados.html",contexto)    


@login_required
@permission_required('sito_admin.can_add_arte')
def listapedidos(request):
    pedidos=Pedido.objects.all()
    print(request.user.email)
    print(request.user.username)
    contexto={
        'pedidos':pedidos
    }

    return render(request,'sitio_admin/listapedidos.html',contexto)

@login_required
@permission_required('sito_admin.can_add_arte')
def detallepedido(request,id):
    pedidodet=Pedido.objects.get(id=id)
    items=ItemPedido.objects.all().filter(pedido=id)

    contexto={
        'items':items,
        'pedidodet':pedidodet

    }

    return render(request,'sitio_admin/detallepedido.html',contexto)

@login_required
@permission_required('sito_admin.can_add_arte')
def cambiarestado(request,id,tipo):
    pedidodet=Pedido.objects.get(id=id)

    pedidodet.estado=tipo
    pedidodet.save()
    return redirect(to="listapedidos")

sitio_admin/templates/sitio_admin/agregararte.html
{% extends 'sitio_admin/base.html' %}
{%load static %}
{%load crispy_forms_tags%}


{% block links %}

{% endblock links %}



{% block contenido %}
<script>
    $(document).ready(function () {
        $('select').selectpicker();
        $('select').addClass("show-tick");
        $('#id_categoria').attr("title","Seleccione categoria")
        $('option').addClass("form-control");
        $("div.filter-option-inner-inner:contains('Nothing selected')").text("Seleccione categoria")
        
    
       
    });
</script>

<section>
    <div class=" container p-5">
        
        <div class="container pl-5 pr-5 pt-0">
        {% if form %}
            <h4 class="text-center">Agregar Arte</h4>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn  btn-secondary mb-5" value="Agregar Arte">
            </form>
        {% endif %}    
        </div>
       
    </div>
</section>


 <!-- Latest compiled and minified CSS -->
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

 <!-- Latest compiled and minified JavaScript -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
 
 <!-- (Optional) Latest compiled and minified JavaScript translation files -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>
     

{% endblock contenido %}

sitio_admin/templates/sitio_admin/agregarjuego.html
{% extends 'sitio_admin/base.html' %}
{%load static %}
{%load crispy_forms_tags%}


{% block links %}
<link rel="stylesheet" href="{% static 'sitio_admin/css/forms.css' %}">
{% endblock links %}



{% block contenido %}

<script>
    $(document).ready(function () {
        $('select').selectpicker();
        $('select').addClass("show-tick");
        $('#id_categoria').attr("title","Seleccione categoria")
        $('option').addClass("form-control");
        $("div.filter-option-inner-inner:contains('Nothing selected')").text("Seleccione categoria")
        
    
       
    });
</script>
<section>
    <div class=" container p-5">
        
        <div class="container pl-5 pr-5 pt-0">
        {% if form %}
            <h4 class="text-center">Agregar Juego</h4>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn  btn-secondary mb-5" value="Agregar Juego">
            </form>
        {% endif %}    
        </div>
       
    </div>
</section>

 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>
    
{% endblock contenido %}

sitio_admin/templates/sitio_admin/base.html
<!doctype html>
{% load static %}
<html lang="es">
  <head>
    <title>Juegarte Admin</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!--Alertas Sweet Alert -->
     <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    
    <script src="{% static 'sitio_admin/javascript/jquery-3.6.0.min.js' %}"></script>
    
    
    {% block links %} {% endblock links %}


  </head>
  <body>
      
      <header>
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <!-- Brand -->
            <a class="navbar-brand" href="{% url 'home' %}">Juegarte Admin</a>
          
            <!-- Toggler/collapsibe Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <!-- Navbar links -->
            <div class="collapse navbar-collapse justify-content-center pr-5" id="collapsibleNavbar">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home' %}">Inicio &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
                </li>
                
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listapedidos' %}">Ver Pedidos</a>
                  </li>
                <li class="nav-item">

                  <a class="nav-link" href="{% url 'listaclientes' %}">Clientes</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'listaempleados' %}">Empleados</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                </li>
              </ul>
            </div>
          </nav>
    </header>



    {% block contenido %}{% endblock contenido %}
   

   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
  </body>
</html>

sitio_admin/templates/sitio_admin/detallepedido.html
{% extends 'sitio_admin/base.html' %}
{% load static %}

{% block links %}
<style>
    .estado{
        margin: auto;
        width: 35% !important;
    }
</style>

{% endblock links %}

{% block contenido %}

<section class="mt-5">
    <div class="container ">
        <div class=" text-center justify-content-center">
            <h4 class="text-center">Informacion Pedido</h4>
            <table class="table table-responsive estado">
                <thead>
                    <th>Estado</th>
                    <th>Fecha</th>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            {{pedidodet.get_estado_display}}
                        </td>
                        <td>
                            {{pedidodet.fecha}} 
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="text-center">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                  Cambiar Estado
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'cambiarestado' pedidodet.id 1 %}">Esperando deposito</a>
                  <a class="dropdown-item" href="{% url 'cambiarestado' pedidodet.id 2 %}">En camino</a>
                  <a class="dropdown-item" href="{% url 'cambiarestado' pedidodet.id 3 %}">Cerrado</a>
                  <a class="dropdown-item" href="{% url 'cambiarestado' pedidodet.id 4 %}">Cancelado</a>
                 
                </div>
              </div>
        </div>
       <div class="mt-5">
        <h4 class="text-center">Items Pedido</h4>
        <table class="table table-striped">
            <thead>
                
                <th class="text-center">Nombre</th>
                <th class="text-center">Precio</th>
                <th class="text-center">Cantidad</th>
                <th class="text-center">Subtotal</th>
                
            </thead>
            <tbody>
               {% for item in items  %}
               <tr>
                <td class="text-center">{{item.producto}}</td>
                <td class="text-center">${{item.precio}}</td>
                <td class="text-center">
                    &nbsp; &nbsp;{{item.cantidad}} &nbsp;&nbsp;
                </td>
                <td class="text-center">${{item.subtotal|floatformat}}</td>
    
                
                
               
                </tr>
               {% endfor %}
               
            </tbody>
            <tfoot>
                <tr><td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    </tr>
                <tr class="table-borderless">
                    <td></td>
                    <td></td>
                    
                    <td></td>
                    <td class="table-secondary text-dark text-center" style="font-weight:700;">Total:</td>
                </tr>
                <tr class="table-borderless">
                    <td></td>
                    
                    <td></td>
                    <td ></td>
                    <td class="table-secondary text-dark text-center" style="font-weight:700;">${{pedidodet.monto}}</td>
                </tr>
                
            </tfoot>
        </table>
       </div>
    </div>

</section>
{% endblock contenido %}

sitio_admin/templates/sitio_admin/editararte.html
{% extends 'sitio_admin/base.html' %}
{%load static %}
{%load crispy_forms_tags%}


{% block links %}
<link rel="stylesheet" href="{% static 'sitio_admin/css/forms.css' %}">
{% endblock links %}



{% block contenido %}

<script>
    $(document).ready(function () {
        $('select').selectpicker();
        $('select').addClass("show-tick");
        $('#id_categoria').attr("title","Seleccione categoria")
        $('option').addClass("form-control");
        $("div.filter-option-inner-inner:contains('Nothing selected')").text("Seleccione categoria")
        
    
       
    });
</script>
<section>
    <div class=" container p-5">
        
        <div class="container pl-5 pr-5 pt-0">
        {% if form %}
            <h4 class="text-center">Modificar Arte</h4>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn  btn-warning mb-5 inline" value="Modificar Arte">
                
            </form>
        {% endif %}    
        </div>
       
    </div>
</section>

 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>
    
{% endblock contenido %}

sitio_admin/templates/sitio_admin/editarjuego.html
{% extends 'sitio_admin/base.html' %}
{%load static %}
{%load crispy_forms_tags%}


{% block links %}
<link rel="stylesheet" href="{% static 'sitio_admin/css/forms.css' %}">
{% endblock links %}



{% block contenido %}

<script>
    $(document).ready(function () {
        $('select').selectpicker();
        $('select').addClass("show-tick");
        $('#id_categoria').attr("title","Seleccione categoria")
        $('option').addClass("form-control");
        $("div.filter-option-inner-inner:contains('Nothing selected')").text("Seleccione categoria")
        
    
       
    });
</script>
<section>
    <div class=" container p-5">
        
        <div class="container pl-5 pr-5 pt-0">
        {% if form %}
            <h4 class="text-center">Modificar Juego</h4>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn  btn-warning mb-5 inline" value="Modificar Juego">
                
            </form>
        {% endif %}    
        </div>
       
    </div>
</section>

 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>
    
{% endblock contenido %}

sitio_admin/templates/sitio_admin/home.html
{% extends 'sitio_admin/base.html' %}
{% load static%}
{% block links %}
    <link rel="stylesheet" href="{% static 'sitio_admin/css/home.css' %}">
{% endblock links %}



{% block contenido %}
<script>
    $(document).ready(function () {
       $("#btnjuegos").click(function(){
        $("#btnjuegos").toggleClass("btn-outline-secondary btn-secondary")
           $("#tablajuegos").fadeToggle("slow")
           $("#btnjuegonuevo").fadeToggle("slow")
       });

       $("#btnarte").click(function(){
        $("#btnarte").toggleClass("btn-outline-secondary btn-secondary")
           $("#tablaarte").fadeToggle("slow")
           $("#btnartenuevo").fadeToggle("slow")
       });

    });



function eliminarjuego(idjuego){

    Swal.fire({
        title:"¿Está seguro que desea eliminar?",
        
        showConfirmButton: true,
        confirmButtonColor: "red",

        showCancelButton: true,
        icon: 'warning'
    }).then(function(result){
        if(result.isConfirmed){
            window.location.href="eliminarjuego/" + idjuego;
        }
    });
   
}

function eliminararte(idarte){

    Swal.fire({
        title:"¿Está seguro que desea eliminar?",
        
        showConfirmButton: true,
        confirmButtonColor: "red",

        showCancelButton: true,
        icon: 'warning'
    }).then(function(result){
        if(result.isConfirmed){
            window.location.href="eliminararte/" + idarte;
        }
    });
   
}
</script>
<section id="producttables">
    

    <div class="container pt-5">
        <h3 class="text-center pt-3 pl-5 pr-5 ml-5 mr-5" ><button id="btnjuegos" type="button" class="btn btn-secondary btn-block btn-lg ">Juegos </button> </h3>
        <div class="text-right pb-2 pr-5" id="btnjuegonuevo"><a href="{% url 'agregarjuego' %}" class="btn btn-outline-success btn-sm">Agregar Juego</a></div>
        <div class="scrollable justify-content-center " id="tablajuegos">
            
            <table class=" table table-responsive-md table-striped table-light  ">
                <thead class="bg-secondary text-light ">
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                
                <tbody class="">
                   {% for item in juegos  %}
                   
                    <tr>
                        <td >{{item.idjuego}}</td>
                        <td>{{item.nombrejuego}}</td>
                        <td>${{item.preciojuego}}</td>
                        <td>{{item.get_estado_display}}</td>
                        <td class="text-center tdbuttons " id="" >
                            <a href="{% url 'editarjuego' item.idjuego %}" class="btn btn-outline-warning"><i class="fas fa-edit"></i></a>
                            <a  class="btn btn-outline-danger" role="button" onclick="eliminarjuego({{item.idjuego}})" ><i class="far fa-trash-alt"></i></a>
                             {% comment %} <a href="{% url 'eliminarjuego' item.idjuego %}" class="btn btn-outline-danger" ><i class="far fa-trash-alt"></i></a> {% endcomment %}
                           
                        
                    </tr>
                   
                   {% endfor %}
                   
                </tbody>
            </table>
        </div>
       
    </div>



    <div class="container pt-5">
        <h3 class="text-center pt-3 pl-5 pr-5 ml-5 mr-5" ><button id="btnarte" type="button" class="btn btn-secondary btn-block btn-lg ">Arte</button></h3>
        <div class="text-right pb-2 pr-5" id="btnartenuevo"><a href="{% url 'agregararte' %}" class="btn btn-outline-success btn-sm">Agregar Arte</a></div>
        <div class="scrollable " id="tablaarte">
            <table class="table   table-responsive-md   table-striped table-light table-bordered ">
                <thead class="bg-secondary text-light ">
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                
                <tbody class="">
                   {% for item in arte  %}
                   
                    <tr>
                        <td >{{item.idarte}}</td>
                        <td>{{item.nombrearte}}</td>
                        <td>${{item.precioarte}}</td>
                        <td>{{item.get_estado_display}}</td>
                        <td class="text-center tdbuttons " id="" ><a href="{% url 'editararte' item.idarte %}" class="btn btn-outline-warning"><i class="fas fa-edit"></i></a>
                             <a  class="btn btn-outline-danger" role="button" onclick="eliminararte({{item.idarte}})" ><i class="far fa-trash-alt"></i></a>
                        
                    </tr>
                   
                   {% endfor %}
                   
                </tbody>
            </table>
        </div>
       
    </div>
</section>


<

{% endblock contenido %}

sitio_admin/templates/sitio_admin/listapedidos.html
{% extends 'sitio_admin/base.html' %}
{% load static %}

{% block contenido %}

<section>
    <div class="container pt-5">
        <h3 class="text-center">Listado de pedidos</h3>
        <table class="table table-responsive-lg table-striped">
            <thead>
                <th>ID</th>
                <th>Fecha</th>
                <th>Total</th>
                <th>Estado</th>
                <th>Cliente</th>
                <th>Detalle</th>

            </thead>
            <tbody>
            {% for pedido in pedidos  %}
                 <tr>
                    <td>{{pedido.id}}</td>
                    <td>{{pedido.fecha}}</td>
                    <td>${{pedido.monto}}</td>
                    <td>{{pedido.get_estado_display}}</td>
                    <td>{{pedido.user}}</td>
                    <td><a href="{% url 'detallepedidoadm' pedido.id %}" class="btn btn-outline-info"><i class="fas fa-info-circle"></i></a></td>
                </tr>
            
            {% endfor %}
               
            </tbody>
        </table>

    </div>
</section>

{% endblock contenido %}